### ISSUE TITLE
Incorrect sorting of file systems by "Used" column 

### ISSUE THREAD

**Issue by NathanaelGandhi** [openmediavault/openmediavault#1107]
Sorting by the "Used" column appears to not respect units. ie. 10MiB > 1TiB. 
This behavior appears in two locations, under Storage > File Systems and Diagnostics > Dashboard. 
Sorting by "Available" or "Total" in both of these places functions as expected. 

1. Go to 'Storage > File Systems'
2. Click on 'Used'
3. See error
4. Click on 'Used' again
5. See error
6. Go to 'Diagnostics > Dashboard'
7. Click on 'Add > File Systems'
8. Click on 'Used' 
9. See error
10. Click on 'Used' again
11. See error

Expecting list items to be ordered by total used size (or %). This should be similar to the function of "Available" or "Total"

![Screenshot from 2021-10-01 22-23-49](https://user-images.githubusercontent.com/36506137/135621386-2c3d96db-b58f-48d7-a24c-9024b4acc146.png)
![Screenshot from 2021-10-01 22-23-37](https://user-images.githubusercontent.com/36506137/135621390-3f8e0f4b-99d1-4b5c-90fb-7ffb7b4f0a97.png)
![Screenshot from 2021-10-01 22-23-59](https://user-images.githubusercontent.com/36506137/135621427-b40fcc4f-5bbb-46b2-9ea7-efabf05a5144.png)
![Screenshot from 2021-10-01 22-23-19](https://user-images.githubusercontent.com/36506137/135621406-7e37ea42-d752-45b9-874f-98cf425b6cc6.png)

- OS version: Linux 5.10.60-v7l+ # 1449 SMP Wed Aug 25 15:00:44 BST 2021 armv7l GNU/Linux
- openmediavault version: 5.6.16-1   
      
- Device: MSI GE62-6QF
- OS: Linux 5.11.0-36-generic # 40~20.04.1-Ubuntu SMP Sat Sep 18 02:14:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Browser: Brave
- Version: 1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit)

**Comment by votdev** [comment]
Yes, that is totally right, the column contains the capacity as a string. I've disabled sorting for this column because development is now fully focused on OMV6.

**Comment by votdev** [comment]
Fixed in `openmediavault 5.6.17` by using the `percentage` property for sorting which is the numerical equivalent for the `used` property.

**Comment by olaulau** [comment]
the bug is still here on OMV6 : not % column, and sort capacity as a string.  

at least, if the sort isn't ok, we should disable it.  
but I think it is an important feature.  

multiple pages have this problem :
filesystems, quota, raid,, lvm, disks, smart ...

**Comment by votdev** [comment]
> the bug is still here on OMV6 : not % column, and sort capacity as a string.

I am sorry but i do not understand what you mean. Please be more precise and explain step by step how to reproduce your issue.
