### ISSUE TITLE
SSH key not importable using GUI

### ISSUE THREAD

**Issue by eloo** [openmediavault/openmediavault#160]
Hi,
i just tried to add an SSH key using the GUI. 
So far so good.. Key was added and could be viewed using the GUI. 
Afterwards i tried to login but it seems not to work.. I've checked the imported key in the /var/lib/openmediavault/ssh/authorized_keys/%u file and it looks all good.
Normal ssh pubkey login from keys using ssh-copy-id works.. 
I also added the key from the openmediavault auth_keys to my personal one.. no success.. but copying it using ssh-copy-id works without any issues.. i also compared the two entries.. didn't see any differences..

Looks really weird to me.. do you have any ideas? Is this maybe a known issue?

I'm using latest OMV on OdroidC2 Armbian Kernel 4.17

Thx

**Comment by votdev** [comment]
Which SSH key did you import? The public key for users in the 'Access Rights Management | Users' section or the public/private key in the 'Systems | Certificates' section?

**Comment by eloo** [comment]
I've imported my personal pubkey in the PublicKey section of my user in OMV. So access rights management | users.

**Comment by votdev** [comment]
Is the user added to the SSH group?

**Comment by eloo** [comment]
yes.. i'm using the user over ssh from another laptop without any issues (ssh added using ssh-copy-id)

**Comment by votdev** [comment]
After creating a new user, added it to the SSH group and append the public key i was able to log in via SSH to the OMV box without problems.

**Comment by eloo** [comment]
hmm interesting.. and your key is only stored in /var/lib/openmediavault/ssh/authorized_keys/%u ?

**Comment by votdev** [comment]
Yes

**Comment by eloo** [comment]
okay.. maybe i should test it with a different user.. 
thanks for the information..  i will give feedback asap

**Comment by datag** [comment]
Had the same issue. The public key was offered but OMV's sshd didn't accept it. I monitored with ```journalctl -f``` while sshing into the machine and got: ```Authentication refused: bad ownership or modes for directory /```

I've got a fresh install of OMV4 on ODROID-HC1 (XU4) and the rootfs-permissions were messed up:
```
root@odroid-hc1:~# ls -ld /
drwxrwxrwt 1 root root 174 May 29  2018 /
```

which I fixed with:
```
root@odroid-hc1:~# chmod og-wt /
root@odroid-hc1:~# ls -ld /
drwxr-xr-x 1 root root 174 May 29  2018 /
```

This seems to be a known issue were builds were defect: https://forum.openmediavault.org/index.php/Thread/23234-ssh-with-public-key-bad-ownership-or-modes-for-directory/

**Comment by mevangelisti** [comment]
I had this exact issue on a fresh install of OMV5.
Thanks so much @datag

**Comment by amykyta3** [comment]
Confirmed this issue still exists in the latest release: 5.3.9

Also noticed that a few of the other root directories had questionable permissions (omitting a bunch of dirs that  were the same):
```
alex@openmediavault:~$ ls -la /
drwxrwxr-x .
drwxrwxr-x ..
lrwxrwxrwx bin -> usr/bin
drwxrwxr-x etc
lrwxrwxrwx lib -> usr/lib
lrwxrwxrwx lib32 -> usr/lib32
lrwxrwxrwx lib64 -> usr/lib64
lrwxrwxrwx libx32 -> usr/libx32
lrwxrwxrwx sbin -> usr/sbin
```

Compared to my Ubuntu desktop:
```
alex@alex-desktop:~$ ls -la /
drwxr-xr-x .
drwxr-xr-x ..
drwxr-xr-x bin
drwxr-xr-x etc
drwxr-xr-x lib
drwxr-xr-x lib32
drwxr-xr-x lib64
drwxr-xr-x libx32
drwxr-xr-x sbin
```

**Comment by ElectronicsSam** [comment]
I just installed release: 5.5.11

And had the exact same issue, I modified / permissions like mentioned above to get SSH working. But should I also modify the other questionable permissions, a lot of folders have rwxrwxrwx rights on them. Or will I brake some OMV functionality by doing that?

**Comment by votdev** [comment]
Problem has been reported to the live-build mailing list: https://www.mail-archive.com/debian-live@lists.debian.org/msg17953.html

Need to verify the response.

**Comment by mi-hol** [comment]
> Problem has been reported to the live-build mailing list: https://www.mail-archive.com/debian-live@lists.debian.org/msg17953.html
> 
> Need to verify the response.

As I understand the reply its a "can NOT reproduce" and hint "check the 'umask' setting in your user
profile" . Guess this would be user profle of OMV's 'admin' user, right?

**Comment by steakhutzeee** [comment]
In OMV public keys are stored in /var/lib/openmediavault/ssh/authorized_keys/%u because there are no home folders for users and so no .ssh directories for them?

I have created my home folder with mkhomedir_helper and in my home dir there is no .ssh dir. This is intended to work this way?

**Comment by gonzaleztroyano** [comment]
I'm having the same issue. 
After importing the key from the GUI, cannot access using SSH.  
On client: 
```
ssh user@SERVER -i .ssh/user -vv
OpenSSH_7.6p1 Ubuntu-4ubuntu0.5, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "SERVER " port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to SERVER  [192.168.56.113] port 22.
debug1: Connection established.
debug1: identity file .ssh/user type 0
debug1: key_load_public: No such file or directory
debug1: identity file .ssh/user-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.9p1 Debia                                          n-10+deb10u2
debug1: match: OpenSSH_7.9p1 Debian-10+deb10u2 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to SERVER:22 as 'user'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2                                          -nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sh                                          a256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-                                          group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ex                                          t-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2                                          -nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sh                                          a2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh                                          .com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256                                          -ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256                                          -ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-25                                          6-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-6                                          4@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-25                                          6-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-6                                          4@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2                                          -nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sh                                          a256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-                                          group14-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp2                                          56,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256                                          -ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256                                          -ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-25                                          6-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-6                                          4@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-25                                          6-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-6                                          4@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none
debug2: compression stoc: none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit                                          > compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit                                          > compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:gLGmOzGi1mWOOKmf6dhc7xH2Ttm+                                          ostwtN/cERjrrz0
debug1: Host 'SERVER' is known and matches the ECDSA host key.
debug1: Found key in /home/user/.ssh/known_hosts:1
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug2: key: .ssh/user (0x564a1a01eef0), explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rs                                          a-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:wpOSevL3o4r9SNzrh0WDGhlXb1aHzgfS+ZB29YkR                                          ofI .ssh/user
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
user@nas.SERVER: Permission denied (publickey).
```

On server `/var/log/auth.log`:

```
Oct 30 14:43:18 nas sshd[11248]: Connection from 192.168.56.109 port 54132 on 192.168.56.113 port 22
Oct 30 14:43:18 nas sshd[11248]: debug1: Client protocol version 2.0; client software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.5
Oct 30 14:43:18 nas sshd[11248]: debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.5 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
Oct 30 14:43:18 nas sshd[11248]: debug1: Local version string SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
Oct 30 14:43:18 nas sshd[11248]: debug1: permanently_set_uid: 111/65534 [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: SSH2_MSG_KEXINIT sent [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: SSH2_MSG_KEXINIT received [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: kex: algorithm: curve25519-sha256 [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: kex: host key algorithm: ecdsa-sha2-nistp256 [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: rekey after 134217728 blocks [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: SSH2_MSG_NEWKEYS sent [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: expecting SSH2_MSG_NEWKEYS [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: SSH2_MSG_NEWKEYS received [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: rekey after 134217728 blocks [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: KEX done [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: userauth-request for user user service ssh-connection method none [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: attempt 0 failures 0 [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: PAM: initializing for "user"
Oct 30 14:43:18 nas sshd[11248]: debug1: PAM: setting PAM_RHOST to "192.168.56.109"
Oct 30 14:43:18 nas sshd[11248]: debug1: PAM: setting PAM_TTY to "ssh"
Oct 30 14:43:18 nas sshd[11248]: debug1: userauth-request for user user service ssh-connection method publickey [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: attempt 1 failures 0 [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: userauth_pubkey: test pkalg rsa-sha2-512 pkblob RSA SHA256:wpOSevL3o4r9SNzrh0WDGhlXb1aHzgfS+ZB29YkRofI [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: temporarily_use_uid: 1001/100 (e=0/0)
Oct 30 14:43:18 nas sshd[11248]: debug1: trying public key file /srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys
Oct 30 14:43:18 nas sshd[11248]: debug1: Could not open authorized keys '/srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys': No such file or directory
Oct 30 14:43:18 nas sshd[11248]: debug1: restore_uid: 0/0
Oct 30 14:43:18 nas sshd[11248]: debug1: temporarily_use_uid: 1001/100 (e=0/0)
Oct 30 14:43:18 nas sshd[11248]: debug1: trying public key file /srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys2
Oct 30 14:43:18 nas sshd[11248]: debug1: Could not open authorized keys '/srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys2': No such file or directory
Oct 30 14:43:18 nas sshd[11248]: debug1: restore_uid: 0/0
Oct 30 14:43:18 nas sshd[11248]: debug1: temporarily_use_uid: 1001/100 (e=0/0)
Oct 30 14:43:18 nas sshd[11248]: debug1: trying public key file /var/lib/openmediavault/ssh/authorized_keys/user
Oct 30 14:43:18 nas sshd[11248]: debug1: fd 4 clearing O_NONBLOCK
Oct 30 14:43:18 nas sshd[11248]: Authentication refused: bad ownership or modes for directory /
Oct 30 14:43:18 nas sshd[11248]: debug1: restore_uid: 0/0
Oct 30 14:43:18 nas sshd[11248]: Failed publickey for user from 192.168.56.109 port 54132 ssh2: RSA SHA256:wpOSevL3o4r9SNzrh0WDGhlXb1aHzgfS+ZB29YkRofI
Oct 30 14:43:18 nas sshd[11248]: Connection closed by authenticating user user 192.168.56.109 port 54132 [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: do_cleanup [preauth]
Oct 30 14:43:18 nas sshd[11248]: debug1: monitor_read_log: child log fd closed
Oct 30 14:43:18 nas sshd[11248]: debug1: do_cleanup
Oct 30 14:43:18 nas sshd[11248]: debug1: PAM: cleanup
Oct 30 14:43:18 nas sshd[11248]: debug1: Killing privsep child 11249
Oct 30 14:43:18 nas sshd[11248]: debug1: audit_event: unhandled event 12
Oct 30 14:45:01 nas CRON[11511]: pam_unix(cron:session): session opened for user root by (uid=0)
Oct 30 14:45:02 nas CRON[11511]: pam_unix(cron:session): session closed for user root
```

**Comment by mi-hol** [comment]
@gonzaleztroyano have you tried to change permissions for /var/lib/openmediavault/ssh/authorized_keys/user?
`chmod 600 /var/lib/openmediavault/ssh/authorized_keys/user`

**Comment by gonzaleztroyano** [comment]
@mi-hol It has been a month since I had the problem, so I can't say for sure if this was the case and/or if there was any modification on my part. 

As far as I can remenber, I did not modify root permissions, these were the ones I had:

![image](https://user-images.githubusercontent.com/44492590/145891024-638f3c24-43b1-4223-b25c-5c5dfb79f09e.png)


The screenshot was taken while I was trying to fix the problem. 

On logs I can see this line:
```
Oct 30 14:43:18 nas sshd[11248]: Authentication refused: bad ownership or modes for directory /
```

Reviewing logs I also noticed that sshd was searching for keys on `/srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys`, but without finding any file. 

So I copied the contents of one file to the other one:
```
root@nas: cp /var/lib/openmediavault/ssh/authorized_keys/user /srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys
```

By default, I realized it has `-rw-------` permission, so I changed it to `-rw-r--r--`. I write down that it gave me an error and doing this it was solved.

I also make the user owner of the file: `chown user:users authorized_keys`

The 2 previuous step was based on [this resource](https://help.ubuntu.com/community/SSH/OpenSSH/Keys#:~:text=The%20authorized_keys%20file%20should%20have,be%20owned%20by%20the%20user.&text=The%20next%20time%20you%20connect,have%20to%20enter%20your%20password.) from Ubuntu webpage.

After doing all this, all was fine. 

![image](https://user-images.githubusercontent.com/44492590/145893547-5f430c59-19a1-4500-b178-41b3bca87001.png)


These are the logs:
```
Oct 30 15:24:53 nas sshd[16530]: debug1: trying public key file /srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys
Oct 30 15:24:53 nas sshd[16530]: debug1: fd 4 clearing O_NONBLOCK
Oct 30 15:24:53 nas sshd[16530]: debug1: /srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys:1: matching key found: RSA SHA256:wpOSevL3o4r9SNzrh0WDGhlXb1aHzgfS+ZB29YkRofI
Oct 30 15:24:53 nas sshd[16530]: debug1: /srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Oct 30 15:24:53 nas sshd[16530]: Accepted key RSA SHA256:wpOSevL3o4r9SNzrh0WDGhlXb1aHzgfS+ZB29YkRofI found at /srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys:1
Oct 30 15:24:53 nas sshd[16530]: debug1: restore_uid: 0/0
Oct 30 15:24:53 nas sshd[16530]: Postponed publickey for user from 192.168.56.109 port 54142 ssh2 [preauth]
Oct 30 15:24:59 nas sshd[16530]: debug1: userauth-request for user user service ssh-connection method publickey [preauth]
[...]
Oct 30 15:24:59 nas sshd[16530]: debug1: PAM: establishing credentials
Oct 30 15:24:59 nas sshd[16530]: pam_unix(sshd:session): session opened for user user by (uid=0)
```

If needed, I can reinstall OpenMediaVault and re-test. I do also have the Virtual Machine still saved. 

I can involve some colleagues who have been performing similar tests as well. 

Waiting for your replies. Maybe is just my fault and I configured something the wrong way.

**Comment by mi-hol** [comment]
> So I copied the contents of one file to the other one:
root@nas: cp /var/lib/openmediavault/ssh/authorized_keys/user /srv/dev-disk-by-id-md-name-nas-RAID5Carpet4You/home/user/.ssh/authorized_keys
By default, I realized it has -rw------- permission, so I changed it to -rw-r--r--. I write down that it gave me an error and doing this it was solved.
I also make the user owner of the file: chown user:users authorized_keys
The 2 previous step was based on this resource from Ubuntu webpage.

Thanks, this info is very helpful

**Comment by dafzor** [comment]
So facing this issue with  6.4.9-1 (Shaitan).

Created a user added a ssh pub key and server rejects it, using password worked fine.

Looking at the log and this thread fixed it by running `chmod og-wt /`

**Comment by homza** [comment]
Same issue (SSH Key Only Authentication doesn't work.
Version = 6.9.10-1 (Shaitan)
root@server:~# ls -ld /
Incorrect-Root-Directory-Permissions 22 root root 4096 Dec 10 17:16 /
Fix = chmod og-wt /
After fix:
root@server:~# ls -ld /
drwxr-xr-x 22 root root 4096 Dec 10 17:31 /
SSH Key Only Authentication now works as expected.

**Comment by orgcontrib** [comment]
@votdev I'd like to clarify whether or not your [statement](https://forum.openmediavault.org/index.php?thread/45109-omv-cannot-import-ssh-key/&postID=328338#post328338) 

> ed25519 SSH key support has been added ONLY for public keys only that can be entered in the user properties.

 holds true for 7.x (maybe even 8.x)
 
 After generating a new ed25519 key pair in the GUI and [converting](https://docs.openmediavault.org/en/stable/administration/services/ssh.html#ssh-convert-rfc4716) its pub key, I tried to import the [files](https://docs.openmediavault.org/en/stable/administration/general/certificates.html#admin-certificate-ssh) over on a 2nd host. It didn't work. I think it should be amended in the official doc.
