### ISSUE TITLE
OMV 4.1.11 SMART device attributes window UI glitch in "Status"

### ISSUE THREAD

**Issue by mackonsti** [openmediavault/openmediavault#176]
Hello to OMV team and warm thanks for all your great and hard work.

Running Arrakis 4.1.11 latest updates on a x86 Intel NUC.

When I logged in today with Chrome (latest 69) on my MacOS, the UI of the window for the SMART attributes of my drive show some CSS/HTML5 components rather than icons?

Please correct me if I am wrong...

Go to : Storage > SMART > Devices tab > select HDD > Information button > Attributes tab in the window that pops up > expand window.

The "Status" column shows something like **mdi-checkbox-blank-circle,x-color-good** instead of icons or human-readable text.

When inspecting with Chrome, I see the whole <TD> part:

`<td class="x-grid-cell x-grid-td x-grid-cell-fonticoncolumn-1243 x-grid-cell-last x-unselectable" style="width:300px;" role="gridcell" tabindex="-1" data-columnid="fonticoncolumn-1243"><div unselectable="on" class="x-grid-cell-inner " style="text-align:center;" id="ext-element-56">mdi mdi-checkbox-blank-circle,x-color-good</div></td>`

I could not verify this on Opera v55 nor in Safari v12 on Mac OS X 10.12.6 because they seem incompatible with the overall site. Only Chrome v69 actually displays the web pages properly.

Thank you for listening, keep up the great work.

![smart-device-information-attributes](https://user-images.githubusercontent.com/1313613/45975971-c4183f80-c045-11e8-82a5-9958445fac02.png)

**Comment by votdev** [comment]
This is already fixed and will be included in openmediavault 4.1.12, see https://github.com/openmediavault/openmediavault/commit/8e469c75d485aada1a754bb8a6765a0c34aac2a1.

**Comment by mackonsti** [comment]
Hi @votdev I just updated to 4.1.12, rebooted the device, but this issue is still there. Can you kindly confirm it's pushed into 4.1.12?
Running OMV on a small Intel-NUC and using Chrome on Mac (the only browser showing the UI properly). Thank you.

**Comment by votdev** [comment]
You have to clear your browser cache.

Regards
Volker

Am 06.10.2018 um 12:13 schrieb MacKonsti:
