### ISSUE TITLE
Cannot assign permissions on shares to users

### ISSUE THREAD

**Issue by Kyngo** [openmediavault/openmediavault#2049]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

When going to Users > Permissions @ <user>, clicking any of the options in any share (Read/Write, Read only, No access) and clicking on “Save” I get this error:

```
: The value "null" is not an object.

OMV\Json\SchemaValidationException: : The value "null" is not an object. in /usr/share/php/openmediavault/json/schema.inc:401
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(289): OMV\Json\Schema->validateObject()
#1 /usr/share/php/openmediavault/json/schema.inc(261): OMV\Json\Schema->validateType()
#2 /usr/share/php/openmediavault/rpc/paramsvalidator.inc(59): OMV\Json\Schema->validate()
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(185): OMV\Rpc\ParamsValidator->validate()
#4 /usr/share/openmediavault/engined/rpc/usermgmt.inc(186): OMV\Rpc\ServiceAbstract->validateMethodParams()
#5 [internal function]: Engined\Rpc\UserMgmt->enumerateUsers()
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array()
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#8 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(613): OMV\Rpc\Rpc::call()
#9 [internal function]: Engined\Rpc\ShareMgmt->getPrivileges()
#10 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array()
#11 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(794): OMV\Rpc\ServiceAbstract->callMethod()
#12 [internal function]: Engined\Rpc\ShareMgmt->setPrivilegesByRole()
#13 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array()
#14 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#15 /usr/sbin/omv-engined(546): OMV\Rpc\Rpc::call()
#16 {main}
```

**To Reproduce**

1. Go to Users > Users
2. Click on a user
3. Select a permission on a share
4. Click save
5. See error

**Expected behavior**

Instead of seeing an error on step 5, you should be able to see a message saying changes have been saved.

**Screenshots**

[Imgur](https://imgur.com/JfLcYkb)

**Reference to Forum**

URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version: `Linux nas 6.12.47+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.12.47-1+rpt1 (2025-09-16) aarch64 GNU/Linux`
- openmediavault version: `8.0-7 (Synchrony)`

**Client (please complete the following information):**

- Device: iPad Air (2025)
- OS: iPadOS 26.1
- Browser: Safari
- Version: Stock

- Device: ASUS ROG Laptop
- OS: Fedora Workstation 43
- Browser: Brave
- Version: 1.84.141 (latest)

**Comment by votdev** [comment]
Thx for reporting. The bug has been already fixed.

**Comment by Kyngo** [comment]
I'm afraid to say it has not been fixed. I've updated to `8.0-8` and still get an error. Perhaps there's something different?

```
: The value "null" is not an object.

OMV\Json\SchemaValidationException: : The value "null" is not an object. in /usr/share/php/openmediavault/json/schema.inc:401
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(289): OMV\Json\Schema->validateObject()
#1 /usr/share/php/openmediavault/json/schema.inc(261): OMV\Json\Schema->validateType()
#2 /usr/share/php/openmediavault/rpc/paramsvalidator.inc(59): OMV\Json\Schema->validate()
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(185): OMV\Rpc\ParamsValidator->validate()
#4 /usr/share/openmediavault/engined/rpc/usermgmt.inc(186): OMV\Rpc\ServiceAbstract->validateMethodParams()
#5 [internal function]: Engined\Rpc\UserMgmt->enumerateUsers()
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array()
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#8 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(613): OMV\Rpc\Rpc::call()
#9 [internal function]: Engined\Rpc\ShareMgmt->getPrivileges()
#10 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array()
#11 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(794): OMV\Rpc\ServiceAbstract->callMethod()
#12 [internal function]: Engined\Rpc\ShareMgmt->setPrivilegesByRole()
#13 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array()
#14 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#15 /usr/sbin/omv-engined(546): OMV\Rpc\Rpc::call()
#16 {main}
```

EDIT: No, it's not cache (at least not client-side or temporary server-side). I cleaned the browser cache and rebooted the Raspberry Pi hosting it. Perhaps there's another cache I'm not aware that requires cleaning?

**Comment by votdev** [comment]
This might be related as well: https://forum.openmediavault.org/index.php?thread/57688-error-trying-to-define-permision-to-created-folders-on-omv8/

**Comment by Kyngo** [comment]
@votdev it seems like a new release is not yet available. Could you please provide an estimate as when this will be available to install? Thanks.

**Comment by votdev** [comment]
The 8.0-8 package that is fixing the issue is out since 24.11.2025.

**Comment by Kyngo** [comment]
I'm afraid not, as I have that package installed and I do not see this fixed. Is there perhaps a cache I'm not aware of that has to be removed?

**Comment by votdev** [comment]
https://github.com/user-attachments/assets/b43778b8-9424-4a42-ba92-bcf1b56d1c93

**Comment by Kyngo** [comment]
https://github.com/user-attachments/assets/302ef943-967f-4677-a67e-45b61c5238b9

**Comment by ryecoaaron** [comment]
Volker, I was able to reproduce.  Here is the omv-engined debug output:

```
omv-engined[511478]: Executing RPC (service=ShareMgmt, method=setPrivilegesByRole, params={"role":"user","name":"testuser","privileges":[{"uuid":"342fa3af-b43d-41b0-96cb-05cdf2cfe191","perms":7}]}, context={"username":"admin","role":1}) ...
omv-engined[511478]: 
omv-engined[511478]: RPC response (service=ShareMgmt, method=setPrivilegesByRole, time=5ms):
{"response":null,"error":{"code":0,"message":": The value \"null\" is not an object.","trace":"OMV\\Json\\SchemaValidationException: : The value \"null\" is not an object. in \/usr\/share\/php\/openmediavault\/json\/schema.inc:401\nStack trace:\n#0 \/usr\/share\/php\/openmediavault\/json\/schema.inc(289): OMV\\Json\\Schema->validateObject()\n#1 \/usr\/share\/php\/openmediavault\/json\/schema.inc(261): OMV\\Json\\Schema->validateType()\n#2 \/usr\/share\/php\/openmediavault\/rpc\/paramsvalidator.inc(59): OMV\\Json\\Schema->validate()\n#3 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(185): OMV\\Rpc\\ParamsValidator->validate()\n#4 \/usr\/share\/openmediavault\/engined\/rpc\/usermgmt.inc(186): OMV\\Rpc\\ServiceAbstract->validateMethodParams()\n#5 [internal function]: Engined\\Rpc\\UserMgmt->enumerateUsers()\n#6 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(124): call_user_func_array()\n#7 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod()\n#8 \/usr\/share\/openmediavault\/engined\/rpc\/sharemgmt.inc(613): OMV\\Rpc\\Rpc::call()\n#9 [internal function]: Engined\\Rpc\\ShareMgmt->getPrivileges()\n#10 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(124): call_user_func_array()\n#11 \/usr\/share\/openmediavault\/engined\/rpc\/sharemgmt.inc(794): OMV\\Rpc\\ServiceAbstract->callMethod()\n#12 [internal function]: Engined\\Rpc\\ShareMgmt->setPrivilegesByRole()\n#13 \/usr\/share\/php\/openmediavault\/rpc\/serviceabstract.inc(124): call_user_func_array()\n#14 \/usr\/share\/php\/openmediavault\/rpc\/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod()\n#15 \/usr\/sbin\/omv-engined(546): OMV\\Rpc\\Rpc::call()\n#16 {main}","http_status_code":400}}
```

**Comment by votdev** [comment]
I'm sorry, the [fix](https://github.com/openmediavault/openmediavault/commit/96b341c33cf620b580fed4d4e36fca0076286249) was applied for `openmediavault 8.0-9`.

**Comment by Kyngo** [comment]
> I'm sorry, the [fix](https://github.com/openmediavault/openmediavault/commit/96b341c33cf620b580fed4d4e36fca0076286249) was applied for `openmediavault 8.0-9`.

Any estimate as to when the release will be available in the Debian repository?

**Comment by votdev** [comment]
> > I'm sorry, the [fix](https://github.com/openmediavault/openmediavault/commit/96b341c33cf620b580fed4d4e36fca0076286249) was applied for `openmediavault 8.0-9`.
> 
> Any estimate as to when the release will be available in the Debian repository?

The package is in the repo now.

**Comment by Kyngo** [comment]
Can confirm it works, thanks a lot @votdev !
