### ISSUE TITLE
Corsair MP510 NVMe SMART status reading failure

### ISSUE THREAD

**Issue by jacksterz** [openmediavault/openmediavault#437]
The SMART data of my new 480Gb Corsair MP510 NVMe drive can not be read in OMV webGUI. The "INFORMATION SECTION" shows up just fine in "Extended information" but the SMART data section fails with this error message: 

**"Read NVMe SMART/Health Information failed: NVMe Status 0x2002"**

It seems that OMV is trying to fetch the data from device "nvme0n1" and that's why the command is failing. The SMART data can be read in the shell with drive name "nvme0" with the command _"smartctl -a -d nvme /dev/nvme0"_

**Comment by votdev** [comment]
Please answer the questions mentioned in https://forum.openmediavault.org/index.php/Thread/28552-NVMe-SMART-status-reading-failure-wrong-drive-name/?s=2727f8237b058d90a84cacd18acfe9607af1ed84.

As told there, I can not reproduce the problem, smartctl can access devices named like /dev/nvma0n1 without problems on Debian 9.

**Comment by jacksterz** [comment]
Hi, I did give the outputs of _"dpkg -l | grep smartmontools"_ and _"smartctl -V"_ in my newest reply to that thread. If it's some other questions you are referring to then I'm not sure what you mean.

Here is my the output of cat /proc/partitions:
```

major minor  #blocks  name

 259        0  468851544 nvme0n1
 259        1     524288 nvme0n1p1
 259        2   30720000 nvme0n1p2
 259        3    8081408 nvme0n1p3
 259        4  429523968 nvme0n1p4
```

**Comment by votdev** [comment]
According to the forum comment it seems adding ``-d nvme`` will solve the problem, despite the fact that i didn't have any troubles to run the command without problems.

**Comment by jacksterz** [comment]
Hi, adding -d does not resolve the issue for me. The device information section always works even without -d but the SMART information section fails with the same error message as without -d.

**Comment by votdev** [comment]
Hmmm, sorry, then i missunderstood your comments. I that case it looks to me a bug in the smartmontools because the documentation tells that it is absolutely correct how OMV calls smartctl.

**Comment by votdev** [comment]
According to the documentation you're using the broadcast namespace when using /dev/nvme0 and that's not exactly what you want when the target is /dev/nvme0n1.

**Comment by jacksterz** [comment]
Looks like there has been some discussion about this issue at smartmontools.org: https://www.smartmontools.org/ticket/1134

**Comment by votdev** [comment]
OK, good to know that it is fixed in Debian 10 (OMV5).

**Comment by auanasgheps** [comment]
Hi,
I am sorry to reply to an old thread, but the issue still exists in OMV5, I am currently running 5.3.2.1 and have the exact same issue as OP:

- nvme drive shows up as nvme0n1
- SMART data is shown correctly if I run via shell smartctl -x /dev/nvme0
- Error message that in the webGUI:
- "Read NVMe SMART/Health Information failed: NVMe Status 0x2002"
- If I run smartctl -x /dev/nvme0 I get some data and the same error as above

smartmontools version is 6.6.-1.
This is a newly installed system.

**Comment by votdev** [comment]
> smartmontools version is 6.6.-1. The issue has been fixed by the smartmontools​ team, but OMV does not pick up the updated package.​

OMV is based on Debian, so OMV uses what Debian privides.

**Comment by auanasgheps** [comment]
Allright. The updated version can be installed via `apt-get install -t buster-backports smartmontools` so the issue can be fixed, but the real question is: should OMV use this backport by default?

**Comment by votdev** [comment]
> should OMV use this backport by default?

OMV will never support that because then you are never sure that interfaces are stable. If you install backports, CLI parameters and the whole behaviour of tools and extensions might change.

**Comment by mi-hol** [comment]
@jacksterz  did openmediavault 5.6.22 resolve the issue?

**Comment by auanasgheps** [comment]
In my case, yes I don't get that error anymore. SMART values are still not filled in the appropriate tab, but I think it's expected; the full report is also shown in OMV GUI.

**Comment by jacksterz** [comment]
> @jacksterz did openmediavault 5.6.22 resolve the issue?

Yes it did :)
