### ISSUE TITLE
Firefox 70.0 breaks access to OMV Web GUI

### ISSUE THREAD

**Issue by m4tt075** [openmediavault/openmediavault#476]
### Description of issue
After the Firefox update to 70.0 I encountered the following situation:
- I can still connect to port 80 of the NAS and obtain the regular OMV login screen
- I can log in using username and password
- Afterwards Firefox loads data from the NAS but stays on an empty, white screen, after the loading is done
- I am apparently logged in. If I want to close the tab, I get the typical pop-up window asking whether I want to leave the page.
- I assume the problem is Firefox-specific, as I can still fully access OMV using Edge.

### Steps to reproduce issue
See above

### Versions report
Latest stable v4.x.x

**Comment by votdev** [comment]
Is any error displayed in the Developer Tools console?

**Comment by m4tt075** [comment]
Yes, it says something like...
`The resource "http://mynas.local/js/omv/module/admin/service/urbackup-server/Settings.js" was blocked because of a MIME-type-conflict ("text/html") (X-Content-Type-Options: nosniff).`

**Comment by m4tt075** [comment]
@votdev ^^ Updated with more detail. Hope this helps...

**Comment by votdev** [comment]
It seems to be related to the urbackup plugin. Something is wrong with the Settings.js file.

Can you uninstall the plugin and try to access the UI again to confirm that.

**Comment by ryecoaaron** [comment]
I haven't changed that page in over a year.  It is also working fine on my OMV4 test VM.

**Comment by m4tt075** [comment]
@votdev I've uninstalled `urbackup` months ago. Maybe it wasn't purged correctly.  Having said that, I just `sshed' into the box. `dpkg -l` does not list `urbackup` anymore either. What I realized in the meantime, is that I can access the web GUI when I use a private window within Firefox, but it still doesn't work in a regular window (for me).

**Comment by ryecoaaron** [comment]
If the plugin isn't installed, clear your browser cache.

**Comment by m4tt075** [comment]
Nope. Tried it before, tried it again just now, doesn't resolve it...
I've been so fed up with this bug, that I've installed Chrome in the meantime. No such problems whatsoever. Pretty sure this is some Firefox bug...

**Comment by ryecoaaron** [comment]
I tried firefox 70 on Windows 10 and Linux.  No issues with or without the plugin installed.  But if you browser knows about urbackup and you uninstalled it, it is either server and/or browser cache.  The apt clean button in omv-extras will clear the server cache.  If it still knows about urbackup after that, something is going on with your firefox.

**Comment by m4tt075** [comment]
First of all, thanks for your help. I appreciate it!

I did `apt clean` and cleared the browser cache again as you suggested. The `urbackup` errors are gone, but I'm still stuck on the white screen. The developer console says:
```console
unreachable code after return statement           ext-all.js:22:366125
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error                 code. ext-all.js:22
    ExtJS 6
        getKeys
        readLocalStorage
        constructor
        F
        anonymous
        create
    <anonym> http://mynas.local/:270
```

**Comment by votdev** [comment]
Please open ``/etc/default/openmediavault`` and set ``OMV_DEBUG_EXTJS=yes``. After that run ``monit restart omv-engined``. Finally go to the browser and try to login. Now you should get a better error message that is hopefully more helpful.

**Comment by m4tt075** [comment]
Done as suggested. Here the output I got:
```console
Unhandled rejection: OpenFailedError: UnknownError The operation failed for reasons unrelated to the database itself and not covered by any other error code.
create@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:325975
a/<@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:317341
at/<@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:302970
Ne@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:298231
ze@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:298715
He@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:298566
background.js:48:303527
Error: Script terminated by timeout at:
s_Ze@https://www.google.com/xjs/_/js/k=xjs.s.de.XSVNAxKJzHE.O/ck=xjs.s.nO4uytA-ERM.L.F4.O/m=Fkg7bd,HcFEGb,IvlUe,MC8mtf,OF7gzc,RMhBfe,T4BAC,TJw5qb,TbaHGc,Y33vzc,ZyRBae,cdos,cr,hsm,iDPoPb,jsa,mvYTse,tg8oTe,uz938c,vWNDde,ws9Tlc,yQ43ff,d,csi/am=BAAAsAiYuwHw_D8UAASCngEAIKAt2GCBFCRkjIUBAYA/d=1/dg=2/ct=zgms/rs=ACT90oEgaxqc1xAaQ6iUeQ5Seo-8dFvYaQ:241:497
s_4g@https://www.google.com/xjs/_/js/k=xjs.s.de.XSVNAxKJzHE.O/ck=xjs.s.nO4uytA-ERM.L.F4.O/m=Fkg7bd,HcFEGb,IvlUe,MC8mtf,OF7gzc,RMhBfe,T4BAC,TJw5qb,TbaHGc,Y33vzc,ZyRBae,cdos,cr,hsm,iDPoPb,jsa,mvYTse,tg8oTe,uz938c,vWNDde,ws9Tlc,yQ43ff,d,csi/am=BAAAsAiYuwHw_D8UAASCngEAIKAt2GCBFCRkjIUBAYA/d=1/dg=2/ct=zgms/rs=ACT90oEgaxqc1xAaQ6iUeQ5Seo-8dFvYaQ:409:433
s_98f@https://www.google.com/xjs/_/js/k=xjs.s.de.XSVNAxKJzHE.O/ck=xjs.s.nO4uytA-ERM.L.F4.O/am=BAAAsAiYuwHw_D8UAASCngEAIKAt2GCBFCRkjIUBAYA/d=1/exm=Fkg7bd,HcFEGb,IvlUe,MC8mtf,OF7gzc,RMhBfe,T4BAC,TJw5qb,TbaHGc,Y33vzc,ZyRBae,cdos,cr,csi,d,hsm,iDPoPb,jsa,mvYTse,tg8oTe, rs=ACT90oEgaxqc1xAaQ6iUeQ5Seo-8dFvYaQ:241:497
uncaught exception: Object
IndexedDB UnknownErr: ActorsParent.cpp:15945
IndexedDB UnknownErr: ActorsParent.cpp:15945
unreachable code after return statement ext-all-debug.js:2713:4
unreachable code after return statement ext-all-debug.js:47824:8
unreachable code after return statement ext-all-debug.js:2713:4
Passwort-Felder sind auf einer unsicheren (http://) Seite vorhanden. Dies ist ein Sicherheitsrisiko, durch das Zugangsdaten gestohlen werden können.
myrs
Unhandled rejection: OpenFailedError: UnknownError The operation failed for reasons unrelated to the database itself and not covered by any other error code.
create@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:325975
a/<@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:317341
at/<@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:302970
Ne@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:298231
ze@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:298715
He@moz-extension://6c88b61a-3b94-4794-b499-2f3e026f096a/dist/background.js:48:298566
background.js:48:303527
uncaught exception: Object
IndexedDB UnknownErr: ActorsParent.cpp:15945
IndexedDB UnknownErr: ActorsParent.cpp:15945
unreachable code after return statement ext-all-debug.js:2713:4
unreachable code after return statement ext-all-debug.js:47824:8
unreachable code after return statement ext-all-debug.js:2713:4
IndexedDB UnknownErr: ActorsParent.cpp:15945
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ext-all-debug.js:132954
IndexedDB UnknownErr: ActorsParent.cpp:15945
```

**Comment by votdev** [comment]
Hmm, something went wrong, the frontend debug files are still not enabled. Maybe try to clear the browser cache and use omv-firstaid to clear the webui cache.

**Comment by votdev** [comment]
> ```
> unreachable code after return statement           ext-all.js:22:366125
> UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error                 code. ext-all.js:22
>     ExtJS 6
>         getKeys
>         readLocalStorage
>         constructor
>         F
>         anonymous
>         create
>     <anonym> http://mynas.local/:270
> ```

I think you're hitting a bug in Firefox 70 which is related to localStorage. According to this [site](https://www.heise.de/newsticker/meldung/Firefox-70-Probleme-mit-dynamischen-JavaScript-Elementen-4572077.html) (german only) you can check if your are affected by visiting https://firefox-storage-test.glitch.me/.

**Comment by m4tt075** [comment]
@votdev : You nailed it! Thank You so much! That was indeed the problem. Toggling `dom.storage.next_gen` to `false` on the `about:config` page fixed it for the time being. 
Again, my sincere thanks for your patience and support!
